---
apiVersion: batch/v1
kind: Job
metadata:
  name: letsencrypt-job
  namespace: jamulus
  labels:
    app: letsencrypt-job
spec:
  template:
    metadata:
      name: letsencrypt-job
      labels:
        app: letsencrypt-job
    spec:
      containers:
      - image: gfpsolutions/k8s-nginx-letsencrypt
        name: letsencrypt-job
        imagePullPolicy: Always
        ports:
        - name: letsencrypt
          containerPort: 80
        env:
        - name: DOMAINS
          value: gfplive.com 
        - name: EMAIL
          value: infrastructure@gfpsolutions.com
        - name: SECRET
          value: letsencrypt-certs
    restartPolicy: Never